# ConvertTo-WPFGrid.ps1

#region OUT_WPFGRIDTDO ; #*------v Out-WpfGridTDO v------
#if(-not (gcm Out-WpfGridTDO -ea 0)){
    function Out-WpfGridTDO {
        <#
        .SYNOPSIS
        Out-WpfGridTDO - Jeff Hick's WPF-based out-gridview alternative; doesn't support -passthru (use Read-InputConsoleChoiceTDO if necc)
        .NOTES
        Version     : 3.0.0
        Author: Jeff Hicks
        Website     :	https://github.com/jdhitsolutions
        Twitter     :	
        CreatedDate : 2026-06-15
        FileName    : Out-WpfGridTDO.ps1
        License     : (none asserted)
        Copyright   : (none asserted)
        Github      : https://github.com/jdhitsolutions/PSScriptTools/blob/main/functions/Out-WpfGridTDO.ps1
        Tags        : Powershell,Certificate,Developoment,output,grid
        AddedCredit : 
        AddedWebsite:	
        AddedTwitter:	
        REVISIONS   :
        * 5:33 PM 6/17/2026 ren ConvertTo-WPFGrid -> Out-WpfGridTDO ; added CBH, defer to pre-loaded copies, added internal defer copy of New-RunspaceCleanupJob
        * 3/3/2023 JH posted vers v3.0.0
        .DESCRIPTION
        Out-WpfGridTDO - Jeff Hick's WPF-based out-gridview alternative; doesn't support -passthru (use Read-InputConsoleChoiceTDO if necc)
        This is a verb-io-hosted variant; defers to pre-existing copies loaded.
        There is a limitation with autogenerated columns if the property
        contains a period or a slash.

        https://social.msdn.microsoft.com/Forums/sqlserver/en-US/f5f752f6-f08d-4d46-9e1e-78a4496eaf12/why-does-not-datagrid-show-values-if-there-are-a-point-82208221-or-82208221-in-header?forum=wpf

        This command is an alternative to Out-GridView. It works much the same way. Run a PowerShell command and pipe it to this command. The output will be displayed in an auto-sized data grid. You can click on column headings to sort. You can resize columns and you can re-order columns. You will want to be selective about which properties you pipe through to this command. See examples.

        You can specify a timeout value which will automatically close the form. If you specify a timeout and the Refresh parameter, then the contents of the datagrid will automatically refreshed using the timeout value as an integer. This will only work when you pipe a PowerShell expression to Out-WpfGridTDO as one command. This will fail if you break the command in the PowerShell ISE or use a nested prompt. Beginning with v2.4.0 the form now has a Refresh button which will automatically refresh the datagrid. You should set a refresh interval that is greater than the time it takes to complete the command.

        Because the grid is running in a new background runspace, it does not automatically inherit anything from your current session. However, you can use the -UserProfile parameter which will load your user profile scripts into the runspace. You can specify a list of locally defined variables to be used in the form. Use the variable name without the $. Finally, you can also use the -InitializationScript parameter and specify a scriptblock of PowerShell code to initialize the runspace. This is helpful when you need to dot source external scripts or import modules not in your module path.

        This command runs the WPF grid in a new runspace so your PowerShell prompt will not be blocked. However, after closing the form you may be left with the runspace. You can use Remove-Runspace to clean up or wait until you restart PowerShell.

        This command requires a Windows platform.

        .PARAMETER InputObject
        Typically the results of a PowerShell command or expression. You should select the specific properties you wish to display.
        .PARAMETER Scriptblock
        Enter a scriptblock that will generate data to be populated in the form
        .PARAMETER Title
        Specify a title for your form
        .PARAMETER Timeout
        By default, the grid will remain displayed until you manually close it. But you can specify a timeout interval in seconds. The minimum accepted value is 5 seconds. If you use this parameter with -Refresh, then the datagrid will be refreshed with results of the PowerShell expression you piped to Out-WpfGridTDO.
        .PARAMETER Refresh
        If you specify this parameter and a Timeout value, this command will refresh the datagrid with the PowerShell expression piped into Out-WpfGridTDO. You should use a value that is longer than the time it takes to complete the command that generates your data.  This parameter will only work if you are using Out-WpfGridTDO at the end of a pipelined expression. See examples.
        .PARAMETER GridLines
        Gridlines option (All|Horizontal|None|Vertical)
        .PARAMETER InitializationScript
        Run this scriptblock to initialize the background runspace
        .PARAMETER UseLocalVariable
        Load locally defined variables into the background runspace
        .PARAMETER UseProfile
        Load your PowerShell profiles into the background runspace
        .INPUTS
        PSObject    
        .EXAMPLE
        PS> Get-Process | Sort-Object WS -Descending |
        PS>     Select-object -first 20 ID,Name,WS,VM,PM,Handles,StartTime |
        PS>         Out-WpfGridTDO -Refresh -timeout 20 -Title "Top Processes"
        Get the top 20 processes based on the value of the WorkingSet property and display selected properties in the WPF Grid. The contents will automatically refresh every 20 seconds. You will need to manually close the form.
        .EXAMPLE
        PS> $vmhost = "CHI-HVR2"
        PS> Get-VM -computername $VMHost | Select Name,State,Uptime,@{Name="AssignedMB";Expression={$_.MemoryAssigned/1mb -as [int]}},
        PS>     @{Name="DemandMB";Expression={$_.MemoryDemand/1mb -as [int]}} |
        PS>         Out-WpfGridTDO -title "VM Report $VMHost" -timeout 30 -refresh -UseLocalVariable VMHost
        Get Hyper-V virtual machine information and refresh every 30 seconds. Because the command is using a locally defined variable it is also being used in the form. Note that this would be written as one long pipelined expression. It is formatted here for the sake of the help documentation.
        .EXAMPLE
        PS> Get-VMData -host CHI-HVR2 |
        PS>     Out-WpfGridTDO -title "VM Data" -refresh -timeout 60 -UseProfile
        This example uses a hypothetical command that might be defined in a PowerShell profile script. Out-WpfGridTDO will load the profile scripts so that the data can be updated every 60 seconds.
        .EXAMPLE
        PS> (Get-ProcessData -Computername $computers).where({$_.WorkingSet -ge 100mb}) |
        PS>     Out-WpfGridTDO -Title "Process Report" -UseLocalVariable computers -InitializationScript {. C:\scripts\Get-ProcessData.ps1} -Refresh -Timeout 30
        This command runs a function that is defined in a script file. In order for the form to refresh, it must also dot source the script which is happening with the InitializationScript parameter. The example is also loading the local $computers variable so that it too is available upon refresh.
        .LINK
        https://github.com/jdhitsolutions/PSScriptTools/blob/main/docs/ConvertTo-WPFGrid.md
        #>
        [cmdletbinding(DefaultParameterSetName = "input")]
        [Alias("ConvertTo-WPFGrid","Out-WpfGrid")]
        [OutputType("none")]
        PARAM(
            [Parameter(ValueFromPipeline, ParameterSetName = "Input",HelpMessage="Object to be displayed")]
                [ValidateNotNullOrEmpty()]
                [PSObject]$InputObject,
            [Parameter(ParameterSetName = "scriptblock", HelpMessage = "Enter a scriptblock that will generate data to be populated in the form")]
                [ValidateNotNullOrEmpty()]
                [Scriptblock]$Scriptblock,
            [Parameter(HelpMessage = "Specify a title for your form")]
                [string]$Title = "Out-WpfGridTDO",
            [Parameter(HelpMessage = "By default, the grid will remain displayed until you manually close it. But you can specify a timeout interval in seconds. The minimum accepted value is 5 seconds. If you use this parameter with -Refresh, then the datagrid will be refreshed with results of the PowerShell expression you piped to Out-WpfGridTDO.")]
                [ValidateScript({$_ -ge 5})]
                [int]$Timeout,
            [Parameter(HelpMessage = "If you specify this parameter and a Timeout value, this command will refresh the datagrid with the PowerShell expression piped into Out-WpfGridTDO. You should use a value that is longer than the time it takes to complete the command that generates your data.  This parameter will only work if you are using Out-WpfGridTDO at the end of a pipelined expression. See examples.")]
                [switch]$Refresh,
            [Parameter(HelpMessage = "Control how grid lines are displayed (All|Horizontal|None|Vertical)")]
                [ValidateSet("All", "Horizontal", "None", "Vertical")]
                [ValidateNotNullOrEmpty()]
                [string]$GridLines = "All",
            [Parameter(HelpMessage = "Run this scriptblock to initialize the background runspace")]
                [scriptblock]$InitializationScript,
            [Parameter(HelpMessage = "Load locally defined variables into the background runspace")]
                [alias("var")]
                [string[]]$UseLocalVariable,
            [Parameter(HelpMessage = "Load your PowerShell profiles into the background runspace")]
                [alias("profile")]
                [switch]$UseProfile
        ) ; 
        BEGIN {
            #region FUNCTIONS_INTERNAL ; #*======v FUNCTIONS_INTERNAL  v======
            #region NEW_RUNSPACECLEANUPJOB ; #*------v New-RunspaceCleanupJob v------
            if(-not (gcm New-RunspaceCleanupJob -ea 0)){
                Function New-RunspaceCleanupJob {            
                    <#
                    You use this function like this:
                    $newrunspace = <code>
                    $pscmd = [powershell]::create()

                    add commands to $pscmd
                    $pscmd.runspace = $newrunspace
                    $handle = $pscmd.beginInvoke()

                    Start a thread job to test if runspace is being used and close it if it is finished
                    New-RunspaceCleanUpJob -handle $handle -powershell $pscmd -sleepinterval 30
                    #>
                    <#
                    .SYNOPSIS
                    New-RunspaceCleanUpJob - test if runspace is being used and close it if it is finished.
                    .NOTES
                    Version     : 3.0.0
                    Author: Jeff Hicks
                    Website     :	https://github.com/jdhitsolutions
                    Twitter     :	
                    CreatedDate : 2026-06-15
                    FileName    : New-RunspaceCleanUpJob.ps1
                    License     : (none asserted)
                    Copyright   : (none asserted)
                    Github      : https://github.com/jdhitsolutions/PSScriptTools/blob/main/functions/New-RunspaceCleanUpJob.ps1
                    Tags        : Powershell,Certificate,Developoment,output,grid
                    AddedCredit : 
                    AddedWebsite:	
                    AddedTwitter:	
                    REVISIONS   :
                    * 3/3/2023 JH posted vers v3.0.0
                    .PARAMETER Handle
                    This should be the System.Management.Automation.Runspaces.AsyncResult object from the BeginInvoke() method.
                    .PARAMETER PowerShell
                
                    .PARAMETER SleepInterval
                    Specify a sleep interval in seconds
                    .PARAMETER Handle
                    This should be the System.Management.Automation.Runspaces.AsyncResult object from the BeginInvoke() method.
                    .PARAMETER PassThru
                    Pass the thread job object to the pipeline
                    .INPUTS
                    PSObject
                    .OUTPUT
                    None,ThreadJob
                    .DESCRIPTION
                    New-RunspaceCleanUpJob - test if runspace is being used and close it if it is finished.

                    .EXAMPLE
                    PS> $newrunspace = <code> ; 
                    PS> $pscmd = [powershell]::create() ; 
                    PS> write-verbose "add commands to $pscmd" ; 
                    PS> $pscmd.runspace = $newrunspace ; 
                    PS> $handle = $pscmd.beginInvoke() ; 
                    PS> write-verbose "Start a thread job to test if runspace is being used and close it if it is finished" ; 
                    PS> New-RunspaceCleanUpJob -handle $handle -powershell $pscmd -sleepinterval 30; 
                    Typical usage demo
                    .LINK
                    https://github.com/jdhitsolutions/PSScriptTools/blob/main/docs/New-RunspaceCleanUpJob.md
                    #>
                    [cmdletbinding()]
                    [OutputType("None", "ThreadJob")]
                    Param(
                        [Parameter(Mandatory, HelpMessage = "This should be the System.Management.Automation.Runspaces.AsyncResult object from the BeginInvoke() method.")]
                            [ValidateNotNullOrEmpty()]
                            [object]$Handle,
                        [Parameter(Mandatory, HelpMessage = ".")]
                            [ValidateNotNullOrEmpty()]
                            [System.Management.Automation.PowerShell]$PowerShell,
                        [Parameter(HelpMessage = "Specify a sleep interval in seconds")]
                            [ValidateRange(5, 600)]
                            [int32]$SleepInterval = 10,
                        [Parameter(HelpMessage = "Pass the thread job object to the pipeline")]
                            [switch]$PassThru
                    )
                    $job = Start-ThreadJob -ScriptBlock {
                        param($handle, $ps, $sleep)
                        #the Write-Host lines are so that if you look at the results of  the thread job
                        #you'll see something you can use for debugging or troubleshooting.
                        Write-Host "[$(Get-Date)] Sleeping in $sleep second loops"
                        Write-Host "Watching this runspace"
                        Write-Host ($ps.runspace | Select-Object -property * | Out-String)
                        #loop until the handle shows as completed, sleeping the the specified
                        #number of seconds
                        do {
                            Start-Sleep -Seconds $sleep
                        } Until ($handle.IsCompleted)
                        Write-Host "[$(Get-Date)] Closing runspace"
                        $ps.runspace.close()
                        Write-Host "[$(Get-Date)] Disposing runspace"
                        $ps.runspace.Dispose()
                        Write-Host "[$(Get-Date)] Disposing PowerShell"
                        $ps.dispose()
                        Write-Host "[$(Get-Date)] Ending job"
                    } -ArgumentList $Handle, $PowerShell, $SleepInterval
                    if ($PassThru) {
                        #Write the ThreadJob object to the pipeline
                        $job
                    }
                }
            }
            #endregion NEW_RUNSPACECLEANUPJOB ; #*------^ END  ^------
            #endregion FUNCTIONS_INTERNAL ; #*======^ END FUNCTIONS_INTERNAL ^======

            Write-Verbose "Starting $($MyInvocation.MyCommand)"
            if ($Refresh -AND ($Timeout -lt 5)) {
                Write-Verbose "Detected a timeout value of $Timeout"
                Write-Verbose "Refresh is set to $Refresh"
                Throw "You must specify a timeout value in seconds when using -Refresh"
            }
            #set a flag for the process block
            if ((Test-IsPSWindows)) {
                #attempt to load the WPF related classes which might or might not be available depending
                #on operating system and PowerSell version

                Try {
                    Write-Verbose "Attempting to load WPF assemblies"
                    Add-Type -AssemblyName PresentationFramework -ErrorAction Stop
                    Add-Type -AssemblyName PresentationCore -ErrorAction Stop

                }
                Catch {
                    Write-Warning "Failed to load WPF required assemblies. This command isn't supported under this version of PowerShell on this platform. $($_.exception.Message)"

                    #bail out out of the command
                    break
                }

            Write-Verbose "Define new runspace"
            $newRunspace = [RunspaceFactory]::CreateRunspace()
            if ($newRunspace.ApartmentState) {
                $newRunspace.ApartmentState = "STA"
            }
            else {
                #This command probably won't run if the ApartmentState can't be set to STA
                #clean up
                $newRunspace.dispose()

                Write-Warning "Incompatible runspace detected. This command will most likely fail on this platform with this version of PowerShell."
                #bail out of the command
                break
            }
            $newRunspace.ThreadOptions = "ReuseThread"
            Write-Verbose "Opening new runspace"
            $newRunspace.Open()

            if ($UseLocalVariable) {
                Write-Verbose "Using local variables"
                Get-Variable -include $UseLocalVariable |
                    ForEach-Object {
                    Write-Verbose "...Adding $($_.name)"
                    $newRunspace.sessionStateProxy.SetVariable($_.name, $_.value)
                }
            }

            Write-Verbose "Defining script command"
            $psCmd = [PowerShell]::Create()
            #code to display the WPF form
            $gridScript = {
                Param(
                    [string]$Title,
                    [ValidateScript( {$_ -ge 5})]
                    [int]$Timeout = 0,
                    [object[]]$Data,
                    [scriptblock]$cmd,
                    [switch]$Refresh,
                    [string]$GridLines
                )

                # It may not be necessary to add these types but it doesn't hurt to include them
                Add-Type -AssemblyName PresentationFramework
                Add-Type -AssemblyName PresentationCore

                    Function _refresh {
                        #this is a function to refresh a UI element
                        Param($element)

                        $element.Dispatcher.invoke("render", [action] {})
                        [System.Threading.Thread]::Sleep(50)
                    }

                #get maximum available working area on the screen
                $s = [System.Windows.SystemParameters]::WorkArea

                $form = New-Object System.Windows.Window
                $form.Title = $Title
                $form.MaxHeight = $s.Height
                $form.MaxWidth = $s.Width

                $form.SizeToContent = [System.Windows.SizeToContent]::WidthAndHeight

                #define a handler when the form is loaded. The scriptblock uses variables defined later
                #in the script
                $form.add_Loaded( {
                        $datagrid.UpdateLayout()

                        foreach ($col in $datagrid.Columns) {
                            #because of the way I am loading data into the grid
                            #it appears I need to set the sorting on each column
                            $col.CanUserSort = $True
                            $col.SortMemberPath = $col.Header
                        }

                        If ($Timeout -gt 0) {
                            $timer.IsEnabled = $True
                            $Timer.Start()
                        }

                        #calculate screen dimensions to center the form
                        $s = [System.Windows.SystemParameters]::WorkArea
                        $form.top = $s.Height / 2 - $form.ActualHeight / 2
                        $form.left = $s.width / 2 - $form.ActualWidth / 2
                        $form.UpdateLayout()
                        $form.focus
                    })

                $Form.Add_closing( {
                        #reserved for future use
                    })
                $Form.Add_closed( {
                        #reserved for future use
                    })
                #Create a grid to hold the datagrid
                $Grid = New-Object System.Windows.Controls.Grid

                $Grid.HorizontalAlignment = "stretch"
                $grid.VerticalAlignment = "stretch"

                #add buttons to close and manually refresh (Issue #34)
                $btnRefresh = New-Object System.Windows.Controls.Button
                $btnRefresh.Content = "Refresh Now"
                $btnRefresh.Height = 25
                $btnRefresh.Width = 80
                $btnRefresh.HorizontalAlignment = "left"
                $btnRefresh.VerticalAlignment = "Top"
                $btnRefresh.Margin = "15,10,0,0"
                $btnRefresh.ToolTip = "click to refresh data from the command"

                $btnRefresh.add_click( {
                        [System.Windows.Input.Mouse]::OverrideCursor = [System.Windows.Input.Cursors]::Wait

                        $status.Text = "...refreshing content. Please wait."
                        _refresh $status

                        $timer.stop()
                        Start-Sleep -seconds 3

                        $datagrid.ItemsSource = Invoke-Command -ScriptBlock $cmd

                        foreach ($col in $datagrid.Columns) {
                            #because of the way I am loading data into the grid
                            #it appears I need to set the sorting on each column
                            $col.CanUserSort = $True
                            $col.SortMemberPath = $col.Header
                        }

                        $script:Now = Get-Date

                        if ($script:count) {
                            $script:count = $Timeout
                            [DateTime]$script:terminate = $now.AddSeconds($timeout)
                            $ts = New-TimeSpan -Seconds $script:count
                            $status.text = " Last updated $script:Now - refresh in $($ts.ToString())"
                        }
                        else {
                            $status.text = " last updated $Script:Now"
                        }
                        if ($refresh) {
                            $timer.start()
                        }
                        $form.title = $Title
                        [System.Windows.Input.Mouse]::OverrideCursor = [System.Windows.Input.Cursors]::Arrow
                    })

                $grid.AddChild($btnRefresh)

                $btnClose = New-Object System.Windows.Controls.Button
                $btnClose.Content = "Close"
                $btnClose.Height = 25
                $btnClose.Width = 80
                $btnClose.HorizontalAlignment = "Right"
                $btnClose.VerticalAlignment = "Top"
                $btnClose.Margin = "0,10,15,0"
                $btnClose.ToolTip = "close the form and quit"

                $btnClose.add_click( {
                        $form.Close()
                    })
                $grid.AddChild($btnClose)

                #create a datagrid
                $datagrid = New-Object System.Windows.Controls.DataGrid
                $datagrid.width = "Auto"
                $datagrid.Height = "Auto"
                $datagrid.VerticalAlignment = "stretch"
                $datagrid.HorizontalAlignment = "stretch"
                $datagrid.margin = "0,50,0,25"

                $datagrid.ColumnWidth = "Auto"
                $datagrid.GridLinesVisibility = $GridLines
                $datagrid.VerticalScrollBarVisibility = [System.Windows.Controls.ScrollBarVisibility]::Auto
                $datagrid.HorizontalScrollBarVisibility = [System.Windows.Controls.ScrollBarVisibility]::Auto
                $datagrid.CanUserSortColumns = $True
                $datagrid.CanUserResizeColumns = $True
                $datagrid.CanUserReorderColumns = $True
                $datagrid.AutoGenerateColumns = $False
                $datagrid.CanUserAddRows = $false
                $datagrid.CanUserDeleteRows = $false
                $datagrid.IsReadOnly = $True
                #enable alternating color rows
                $datagrid.AlternatingRowBackground = "gainsboro"

                $DataTable = New-Object System.Data.DataTable

                #create headers
                $data[0].PSObject.properties.Name |
                ForEach-Object {
                    if ($DataTable.columns.caption -NotContains $_) {
                        [void]$DataTable.Columns.add($_)
                    }
                }
                foreach ($obj in $data) {
                    $props = $obj.PSObject.Properties
                    [void]$DataTable.rows.add($props.value)
                }

                for ($i = 0; $i -lt $DataTable.Columns.Count; $i++) {
                    $col = New-Object System.Windows.Controls.DataGridTextColumn
                    $col.Header = $DataTable.Columns[$i].ColumnName
                    $col.Binding = New-Object system.Windows.data.binding("[$i]")
                    [void]$dataGrid.Columns.Add($col)
                }
                write-verbose "returning $($DataTable.Rows.Count) rows"

                $dataGrid.ItemsSource = $DataTable.DefaultView

                # $datagrid.ItemsSource = $data

                foreach ($col in $datagrid.Columns) {
                    #because of the way I am loading data into the grid
                    #it appears I need to set the sorting on each column
                    $col.CanUserSort = $True
                    $col.SortMemberPath = $col.Header
                }
                $Grid.AddChild($datagrid)

                $status = New-Object System.Windows.Controls.TextBlock
                $status.Height = 20
                $status.Background = "lightgray"
                $status.VerticalAlignment = "bottom"
                $status.HorizontalAlignment = "stretch"
                $status.Width = "Auto"

                $Grid.AddChild($status)

                $form.AddChild($Grid)

                $script:Now = Get-Date
                # define a timer to automatically dismiss the form. The timer uses a 1 second interval tick
                if ($Timeout -gt 0) {
                    [int]$script:count = $Timeout
                    $timer = New-Object System.Windows.Threading.DispatcherTimer
                    [DateTime]$script:terminate = $now.AddSeconds($timeout)
                    $timer.Interval = [TimeSpan]"0:0:1.00"

                    $timer.add_tick( {
                            $ts = New-TimeSpan -seconds $script:count
                            if ((Get-Date) -lt $script:terminate -AND $Refresh) {
                                $status.text = " Last updated $script:Now - refresh in $($ts.ToString())"
                                $script:count--
                            }
                            elseif ( (Get-Date) -lt $script:terminate) {
                                $status.text = " Last updated $script:Now - closing in $($ts.ToString())"
                                $script:count--
                            }
                            else {
                                $timer.stop()
                                if ($Refresh) {
                                    $form.Title = "$Title ...refreshing content. Please wait."
                                    [System.Windows.Input.Mouse]::OverrideCursor = [System.Windows.Input.Cursors]::Wait
                                    $datagrid.ItemsSource = Invoke-Command -ScriptBlock $cmd

                                    foreach ($col in $datagrid.Columns) {
                                        #because of the way I am loading data into the grid
                                        #it appears I need to set the sorting on each column
                                        $col.CanUserSort = $True
                                        $col.SortMemberPath = $col.Header
                                    }
                                    $script:count = $timeout
                                    $script:now = Get-Date
                                    [DateTime]$script:terminate = $now.AddSeconds($timeout)
                                    $ts = New-TimeSpan -Seconds $script:count
                                    $status.text = " Last updated $script:Now - refresh in $($ts.ToString()) seconds"
                                    $Timer.Start()
                                    $form.title = $Title
                                    [System.Windows.Input.Mouse]::OverrideCursor = [System.Windows.Input.Cursors]::Arrow
                                }
                                else {
                                    $form.close()
                                }
                            }
                        })
                }
                else {
                    $status.text = " last updated $Script:Now"
                }

                $form.ShowDialog()
            }

            If ($UseProfile) {
                Write-Verbose "Loading user profiles"
                $profiles = $profile.AllUsersAllHosts, $profile.AllUsersCurrentHost,
                $profile.CurrentUserAllHosts, $profile.CurrentUserCurrentHost
                foreach ($file in $profiles) {
                    if (Test-Path -Path $file) {
                        [void]$psCmd.AddScript($file)
                    }
                }
            }
            if ($InitializationScript) {
                Write-Verbose "Loading an initialization scriptblock"
                [void]$psCmd.AddScript($InitializationScript)
            }

            [void]$psCmd.AddScript($gridScript)

            #initialize a list to hold all processed objects
            $data = [System.Collections.Generic.list[object]]::new()
            }
            else {
                $bail = $True
                Write-Warning "This command requires a Windows platform"
                break
            }
        } #begin

        Process {
            #add each incoming object to the data array
            if ($psCmdlet.ParameterSetName -eq 'Input') {
                Write-Verbose "Adding input to data"
                if ($InputObject -is [array]) {
                    $data.AddRange($InputObject)
                }
                else {
                    $data.Add($InputObject)
                }
            }
            else {
                Write-Verbose "Invoking scriptblock"
                $data = Invoke-Command -ScriptBlock $Scriptblock
            }
        } #process

        End {
            Write-Verbose "Updating PSBoundParameters"
            $PSBoundParameters.Data = $data
            [void]$PSBoundParameters.remove("InputObject")
            if ($PSBoundParameters.ContainsKey("UseProfile")) {
                [void]$PSBoundParameters.Remove("UseProfile")
            }

            if ($psCmdlet.ParameterSetName -eq 'input') {

                #parse the invocation to get the pipelined expression up to this command
                #Write-verbose $($MyInvocation | Out-string)
                Write-Verbose "Parsing $($MyInvocation.line) into a scriptblock"
                Try {
                    $cmd = [scriptblock]::Create($MyInvocation.line.substring(0, $MyInvocation.line.LastIndexOf("|")))
                }
                Catch {
                    Write-Warning "Error created the cmd scriptblock: $($_.exception.message)"
                    if ($Refresh) {
                        Write-Warning "Failed create an invocation scriptblock. In order to refresh run your pipelined expression as a single expression with no breaks."
                    }
                }
            }
            else {
                $cmd = $Scriptblock
            }

            $PSBoundParameters.cmd = $cmd
            Write-Verbose "Refresh command: $cmd"

            Write-Verbose "Sending PSBoundParameters to runspace"

            [void]$psCmd.AddParameters($PSBoundParameters)
            $psCmd.Runspace = $newRunspace
            Write-Verbose "Begin Invoke()"
            $handle = $psCmd.BeginInvoke()

            $ThreadJob = New-RunspaceCleanupJob -Handle $handle -powerShell $psCmd -sleep 30 -PassThru
            Write-Verbose "Created monitoring ThreadJob $($ThreadJob.id)"
            Write-Verbose "Ending $($MyInvocation.MyCommand)"

        } #end

    } #close function-
#} ; 
#endregion OUT_WPFGRIDTDO ; #*------^ END Out-WpfGridTDO ^------